### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by pablothobias** [pablothobias/video-maker#3]
## Orquestrador
- [x] Perguntar pelo termo
- [x] Perguntar pelo prefixo
- [x] Iniciar robô de texto
- [x] Iniciar robô de imagens
- [ ] Iniciar robô do vídeo
- [ ] Iniciar robô do YouTube

## Robô de texto
- [x] Estrutura de dados
- [x] Pegar conteúdo do Wikipedia
- [x] Limpar conteúdo
- [x] Quebrar em sentenças
- [x] Pegar Interpretação do Watson
- [x] Adicionar tags
- [x] Salvar estrutura de dados

## Robô de imagens
- [x] Carregar estrutura de dados
- [x] Buscar imagens no Google Imagens
- [x] Baixar Imagens
- [x] Salvar estrutura de dados

## Robô de vídeo
- [ ] Preparar/redimensionar imagens
- [ ] Criar as sentenças com imagens
- [ ] Criar thumbnail para o vídeo
- [ ] Renderizar o vídeo com After Effects
